///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.zeroturnaround:zt-exec:1.12
//DEPS com.fasterxml.jackson.core:jackson-databind:2.17.1
//JAVA 17
//FILES ExampleInfo.json

/*
 * Integration test launcher for brave-starter
 * Generated by scaffold_integration_test.py on 2025-08-01 12:33:39
 */

import com.fasterxml.jackson.databind.*;
import org.zeroturnaround.exec.*;
import java.nio.file.*;
import java.util.concurrent.TimeUnit;
import static java.lang.System.*;

record ExampleInfo(
    int timeoutSec, 
    String[] successRegex, 
    String[] requiredEnv,
    String[] setupCommands,
    String[] cleanupCommands
) {}

public class RunBraveStarter {
    
    public static void main(String... args) throws Exception {
        Path configPath = Path.of("integration-tests/ExampleInfo.json");
        ExampleInfo cfg = new ObjectMapper().readValue(configPath.toFile(), ExampleInfo.class);

        // Verify required environment variables
        for (String envVar : cfg.requiredEnv()) {
            if (getenv(envVar) == null) {
                err.println("❌ Missing required environment variable: " + envVar);
                exit(1);
            }
        }

        try {
            
            // Build and run the main application
            out.println("🏗️  Building brave-starter...");
            runCommand(new String[]{"./mvnw", "clean", "package", "-q", "-DskipTests"}, 300);

            out.println("🚀 Running brave-starter...");
            
            // Create persistent log file for debugging
            Path logDir = Paths.get("../../integration-testing/logs/integration-tests");
            Files.createDirectories(logDir);
            Path logFile = logDir.resolve("brave-starter-spring-boot-" + System.currentTimeMillis() + ".log");
            
            ProcessResult result = new ProcessExecutor()
                .command("./mvnw", "spring-boot:run", "-q")
                .timeout(cfg.timeoutSec(), TimeUnit.SECONDS)
                .redirectOutput(Files.newOutputStream(logFile))
                .redirectErrorStream(true)
                .execute();
            
            int exitCode = result.getExitValue();

            // Verify output patterns
            String output = Files.readString(logFile);
            out.println("✅ Verifying output patterns...");
            
            int failedPatterns = 0;
            for (String pattern : cfg.successRegex()) {
                if (output.matches("(?s).*" + pattern + ".*")) {
                    out.println("  ✓ Found: " + pattern);
                } else {
                    err.println("  ❌ Missing: " + pattern);
                    failedPatterns++;
                }
            }

            // Display captured output for debugging
            out.println("\n📋 Captured Application Output:");
            out.println("━".repeat(80));
            
            // Show MCP Brave search response
            String[] lines = output.split("\n");
            boolean captureOutput = false;
            int outputLines = 0;
            for (String line : lines) {
                if (line.contains("QUESTION:")) {
                    captureOutput = true;
                }
                if (captureOutput) {
                    out.println(line);
                    outputLines++;
                    if (outputLines > 50) {
                        out.println("... (truncated, see full log)");
                        break;
                    }
                }
            }
            out.println("━".repeat(80));
            out.println("📁 Full Spring Boot log: " + logFile.toAbsolutePath());

            if (exitCode != 0) {
                err.println("❌ Application exited with code: " + exitCode);
                exit(exitCode);
            }

            if (failedPatterns > 0) {
                err.println("❌ Failed pattern verification: " + failedPatterns + " patterns missing");
                exit(1);
            }

            out.println("🎉 Integration test completed successfully!");

        } finally {
        }
    }

    private static void runCommand(String[] cmd, int timeoutSec) throws Exception {
        ProcessResult result = new ProcessExecutor()
            .command(cmd)
            .timeout(timeoutSec, TimeUnit.SECONDS)
            .redirectOutput(System.out)
            .redirectError(System.err)
            .execute();
            
        int exit = result.getExitValue();
        if (exit != 0) {
            throw new RuntimeException("Command failed with exit code " + exit + ": " + String.join(" ", cmd));
        }
    }
}