///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.zeroturnaround:zt-exec:1.12
//DEPS com.fasterxml.jackson.core:jackson-databind:2.17.1
//JAVA 17
//FILES ExampleInfo.json

/*
 * Integration test launcher for helloworld
 * Generated by scaffold_integration_test.py on 2025-07-30 20:39:16
 */

import com.fasterxml.jackson.databind.*;
import org.zeroturnaround.exec.*;
import java.nio.file.*;
import java.util.concurrent.TimeUnit;
import static java.lang.System.*;

record ExampleInfo(
    int timeoutSec, 
    String[] successRegex, 
    String[] requiredEnv,
    String[] setupCommands,
    String[] cleanupCommands
) {}

public class RunHelloworld {
    
    public static void main(String... args) throws Exception {
        Path configPath = Path.of("integration-tests/ExampleInfo.json");
        ExampleInfo cfg = new ObjectMapper().readValue(configPath.toFile(), ExampleInfo.class);

        // Verify required environment variables
        for (String envVar : cfg.requiredEnv()) {
            if (getenv(envVar) == null) {
                err.println("❌ Missing required environment variable: " + envVar);
                exit(1);
            }
        }

        try {
            
            // Build and run the main application
            out.println("🏗️  Building helloworld...");
            runCommand(new String[]{"./mvnw", "clean", "package", "-q", "-DskipTests"}, 300);

            out.println("🚀 Running helloworld...");
            Path logFile = Files.createTempFile("integration-test", ".log");
            
            ProcessResult result = new ProcessExecutor()
                .command("./mvnw", "spring-boot:run", "-q")
                .timeout(cfg.timeoutSec(), TimeUnit.SECONDS)
                .redirectOutput(Files.newOutputStream(logFile))
                .redirectErrorStream(true)
                .execute();
            
            int exitCode = result.getExitValue();

            // Verify output patterns
            String output = Files.readString(logFile);
            out.println("✅ Verifying output patterns...");
            
            // Show actual captured output for manual verification
            out.println("📋 Captured Application Output:");
            out.println("---");
            // Show key lines that contain the patterns we're looking for, plus context
            String[] lines = output.split("\n");
            boolean inAssistantResponse = false;
            
            for (int i = 0; i < lines.length; i++) {
                String trimmed = lines[i].trim();
                
                // Always show these key lines
                if (trimmed.contains("Spring AI") || trimmed.contains("USER:") || 
                    trimmed.contains("Hello World") || trimmed.contains("demo completed")) {
                    out.println("  " + trimmed);
                    inAssistantResponse = false;
                }
                // Handle ASSISTANT responses (which may be multi-line)
                else if (trimmed.contains("ASSISTANT:")) {
                    out.println("  " + trimmed);
                    inAssistantResponse = true;
                }
                // Show lines following ASSISTANT: that contain content
                else if (inAssistantResponse && !trimmed.isEmpty() && 
                         !trimmed.startsWith("2025-") && // Skip log timestamps
                         !trimmed.startsWith("[INFO]")) { // Skip Maven messages
                    out.println("  " + trimmed);
                    // Stop after we hit another section or empty content area
                    if (i + 1 < lines.length && lines[i + 1].trim().isEmpty()) {
                        // Check if next non-empty line is still part of response
                        boolean foundNextSection = false;
                        for (int j = i + 1; j < lines.length && !foundNextSection; j++) {
                            String nextLine = lines[j].trim();
                            if (!nextLine.isEmpty()) {
                                if (nextLine.contains("Hello World") || nextLine.contains("demo completed") ||
                                    nextLine.startsWith("2025-")) {
                                    inAssistantResponse = false;
                                    foundNextSection = true;
                                }
                                break;
                            }
                        }
                    }
                }
            }
            out.println("---");
            
            int failedPatterns = 0;
            for (String pattern : cfg.successRegex()) {
                if (output.matches("(?s).*" + pattern + ".*")) {
                    out.println("  ✓ Found: " + pattern);
                } else {
                    err.println("  ❌ Missing: " + pattern);
                    failedPatterns++;
                }
            }
            

            Files.deleteIfExists(logFile);

            if (exitCode != 0) {
                err.println("❌ Application exited with code: " + exitCode);
                exit(exitCode);
            }

            if (failedPatterns > 0) {
                err.println("❌ Failed pattern verification: " + failedPatterns + " patterns missing");
                exit(1);
            }

            out.println("🎉 Integration test completed successfully!");

        } finally {
        }
    }

    private static void runCommand(String[] cmd, int timeoutSec) throws Exception {
        ProcessResult result = new ProcessExecutor()
            .command(cmd)
            .timeout(timeoutSec, TimeUnit.SECONDS)
            .redirectOutput(System.out)
            .redirectError(System.err)
            .execute();
            
        int exit = result.getExitValue();
        if (exit != 0) {
            throw new RuntimeException("Command failed with exit code " + exit + ": " + String.join(" ", cmd));
        }
    }
}